---
title: "Miscellanous datasets"
output: 
  html_document:
   number_sections: false
   highlight: tango
   css: style.css
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



* [Activite et frequence Cardiaque](datasets/activite_FC.csv)
* [Biomass diversity](datasets/Biomass_diversity.csv)
* [Analyse géochimique de sols](datasets/donnees_sols.txt)
* [Morphologie des chauve souris](datasets/bats.csv)
* [Cacao](datasets/cafe_guyana.csv) Les qualités de différentes variétés de Cacao.
* [Croissance](datasets/growth_data.txt)
* [Comptage du nombre d'espèces de plantes](datasets/plant_species.txt)
* [Fourmis](datasets/Fourmis.txt)
* [Flétan](datasets/GroundfishExtraction.csv)
* [Frequence Cardiaque, plan équilibré](datasets/FreqCardiaqueEq.txt)
* [Frequence Cardiaque, plan déséquilibré](datasets/FreqCardiaqueDes1.txt)
* [Grenouilles de Californie](datasets/Grenouille.don)
* [Intima Media](datasets/Intima_Media.txt)
* [Jour du dépassement](datasets/overshootday_overview.csv) Etude de l'empreinte écologique à partir des données de [Global Footprint Network](https://www.footprintnetwork.org/)
* [ParcourSup2023](datasets/parcoursup2023.csv)
* [Manchots](datasets/Manchots.csv)
* [Palangre](datasets/LonglineExample.csv)
* [Pins](datasets/Pin.txt)
* [Pollen](ss700.csv)
* [Pollution US](datasets/USAIR2.DAT)
* [Qualité de vie](datasets/QteVie.csv) provient de l'OCDE et concerne des indicateurs de qualité de vie en 2015. 
* [Samares](datasets/samares_small.xlsx)
* [SamaresEq](datasets/SamaresEq.txt)
* [SamaresEq_disp](datasets/SamaresEq_disp.csv)
