---
title: "Cours niveau L3"
output: 
  html_document:
   toc: true
   toc_float: true
   logo: LogoAgrocampusOuest.jpg
   number_sections: false
   highlight: tango
   css: style.css
---




```{r setup_teaching, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

# Démarche statistique 

Ce cours est une introduction à l'analyse de données au sens large. 

Il porte sur 

* La manipulation et la visualisation de données

* La mise en place de tests statistiques dans le cadre simple du modèle linéaire


## Objectif 

* Trier, représenter des données

* Extraire des propriétés simple des données (résumés numériques, lien entre deux variables, lien entre plusieurs variables)

* Mettre en place une démarche de test statistique pour pouvoir valider ou invalider une hypothèse expérimentale telle que par exemple "Le consommateur évalue plus favorablement le recette du jus d'orange le plus sucré".de la mise en place de l'expérience jusqu'à la conclusion.

* Etre critique sur les limites de sméthodes mises en oeuvre

## Moyens 

Les analyses sont développés sur le logiciel [R](https://www.r-project.org/).  

## Evaluations

* Mini quizz au cours de l'année
* Un (ou deux) devoir(s) sur table 
* Un projet : soutenance de projet le *27 janvier 2023* ( 3 séances de permamence sont prévues). Le projet se fait par binôme sur des données que vous avez la charge de trouver.



## Les ressources

### Analyse descriptive 

* [Analyse descriptive des données](http://marieetienne.github.io/demarche_stat_partie2/_presentation/a_descriptive.html)

* [Analyse en composantes principales](http://marieetienne.github.io/demarche_stat_partie2/_presentation/acp.html)

### Modèle linéaire

* [Démarche statistique : introduction](http://marieetienne.github.io/demarche_stat_partie2/_presentation/demarche_statistique.html)

* [Analyse de la variance à 1 facteur](http://marieetienne.github.io/demarche_stat_partie2/_presentation/anova.html)

* [Analyse de la variance à 2 facteurs](http://marieetienne.github.io/demarche_stat_partie2/_presentation/anova2.html)

* [Régression simple](http://marieetienne.github.io/demarche_stat_partie2/_presentation/regression_simple.html)

* [Analyse de la covariance](http://marieetienne.github.io/demarche_stat_partie2/_presentation/ancova.html)

* [Régression multiple](http://marieetienne.github.io/demarche_stat_partie2/_presentation/regression.html)

### Introduction aux plans d'expériences

<!-- - [Plan d'expérience](http://marieetienne.github.io/demarche_stat_partie2/_presentation/plan_exp.html) -->


Les  TD  sont disponibles sur la page des [énonces de TD](https://marieetienne.github.io/demarche_statistique_AAgro/)
