---
title: "M2 courses"
output: 
  html_document:
   toc: true
   toc_float: true
   logo: INSTITUT_AGRO_Rennes-Angers_CMJN_png
   number_sections: false
   highlight: tango
   css: style.css
---




```{r setup_teaching, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```


# Useful tools for a reproducible science

[This course](https://marieetienne.github.io/reproductibilite/_presentation) is a basic introduction of the control versionning system [git](https://git-scm.com/). We will also make use  of the Github plateform.

You can find the book written collaboratively by students as a project for the Online Collaborative Resources course [here](https://marieetienne.github.io/MODE_reproduciblescience/) and the material of the git intro is [here](https://marieetienne.github.io/reproductibilite/_presentation/english_version.html)


## Prerequisites

Attending this course requires 

   - a functionnal installation of git, which can be downloaded and installed [following this link](https://git-scm.com/downloads) (please click on the display on the right portion of the page).
   - a Github account. Be careful, the Github platform is highly noticeable and will provide you with a professional showcase, it can be visited by potential recruiters (so avoid login names such as bogoss, turlutu, toto or anything of that style).


# Data Vizualisation 

[Introduction to Data Vizualization](https://marieetienne.github.io/Vizualisation/_presentation/visu_intro.html)

[Spatial data vizualization](https://marieetienne.github.io/Vizualisation/_presentation/maps.html)

# Bayesian Model for Ecology

This course is open to students from Datascience and MODE.

The slides are available  [here](https://marieetienne.github.io/bayesian_and_ecology/_presentation/#1)

Implementing your own Metropolis Hastings algorithm  [here](https://marieetienne.github.io/bayesian_and_ecology/_presentation/simpleMCMC.html)

A first example using JAGS  [here](https://marieetienne.github.io/bayesian_and_ecology/_presentation/IllustrationMCMC.html)

Some gentle reminders on classical probability distributions frequently used in Bayesian modelling approaches [here](https://marieetienne.github.io/bayesian_and_ecology/_presentation/LoiProbas.html))


Presentation count data tutorial available  [here](slides/Presentation_pup.pdf)
Count data tutorial available  [here](slides/TD_Pup2.pdf) 

# ALEA : stochastic model in ecology 

* [TD1 content](https://marieetienne.github.io/MODE/_presentation/TD1.html)
* [TD2 content](https://marieetienne.github.io/MODE/_presentation/TD2.html)
* [Processus POisson Cours TD](https://marieetienne.github.io/MODE/_presentation/coursTD_ppd ...html)


# All you want to know on linear modelling

As part of the Tropical Forest Ecology Master in Kourou, French Guyana, I teach a 15hours course on linear modelling. Since 2021, online teaching has becomed a potential option (at least it was in 2021 and 2022). Therefore I have recorded my lectures. The whole course (in French) is available on [this page](linearmodel.html) 

