---
title: "News"
output: 
  html_document:
   toc: false
   toc_float: false
   number_sections: false
   highlight: tango
   css: style.css
   includes:
     # after_body: extLogo.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
- Septembre 2024, I am now Associate Professor at [ENSAI](www.ensai.fr) in Rennes.

- The next [Bayes At Cirm Workshop](https://bayesatcirm.github.io/2023/) is planned on October, 30th  2023.

- Youhou !! On December, 9th Baptiste will defend his PhD, Well done Baptiste! 

-  a new paper as part of Baptiste Alglave PhD. Identifying fish spawning grounds by combining catch declarations and scientific survey data [pdf](https://hal.archives-ouvertes.fr/hal-03674691/document)

-  a new paper as part of Baptiste Alglave PhD. Combining scientific survey and commercial catch data to map fish distribution ( [here](https://academic.oup.com/icesjms/article/79/4/1133/6543974) ).

- The next International Statistical Ecology Conference is in Cape Town, in July 2022. For those concerned about money or carbon footprint, the GDR ecostat is planning a French Hub in Lyon. See you there.

- Nathalie Peyrard and Olivier Gimenez manage to convince quite a bunch of people to write a book on the use of latent variables models in ecology. [english}(https://www.iste.co.uk/book.php?id=1859) or [French](https://www.istegroup.com/en/produit/approches-statistiques-pour-les-variables-cachees-en-ecologie/) version.
 
- Youhou !!  I have received my Habilitation. please find my [presentation](https://marieetienne.github.io/HDR/_presentation/) and my [manuscript](MesPapiers/2021_hdr_etienne.pdf) 

- October 2021: I will defend my Habilitation to mentor research on October 15th at Agrocampus Ouest. 
 
- August 2021: The fifth FinistR bootcamp will take place in August 2021 in Roscoff : [finistR2021](https://stateofther.github.io/finistR2021/)
 
- July 2021: [Les rencontres R à AgroParisTech](https://paris2021.rencontresr.fr/)

- April 2021: Presentation. Identifying stationnary phases in animal movement during the invited session on Movement ecoology at [CNC21](https://cnc21.sciencesconf.org/resource/page/id/6) 

- August 2020: The fourth FinistR bootcamp will take place in August 2020 in Roscoff : [finistR2020](https://stateofther.github.io/finistR2020/)
 
- June 2020:  Presentation. The Langevin model: a continuous time
movement model to understand habitat selection [Virtual International Statistical Ecology Conference (vISEC2020)](https://www.isec2020.org/) 

- February 2020: Agrocampus Ouest will be hosting the [6$^\mbox{th}$ annual GdR ecostats](https://gdrecostat2020.sciencesconf.org/) meeting and the third edition of the [Moving2Gather Workshop](https://gdrecostat2020.sciencesconf.org/). 

- September 2019: The paper for trajectories segmentation is out in Journal of Animal Ecology  [Here](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/1365-2656.13105)

- September 2019. I will give a course on Statistical Modelling for biological Data. The course will take place in Agrocampus Ouest from November 25th to November 29th. Deadline for regisration is November, 1st. Please contact me if you need more information. 

- August 2019: The paper on Langevin model for habitat selection is published in Methods in Ecology and Evolution [Here](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13275)


- July 2019: The next edition will take place in [Agrocampus Ouest](http://www.agrocampus-ouest.fr) in March, 11th, 13th 2020. This will be a follow up of the annual meeting of the [GdR Ecostat](https://sites.google.com/site/gdrecostat/) at the same place.
 
 - April 2019: The third FinistR bootcamp will take place in August 2019 in Roscoff : [finistR2019](https://stateofther.github.io/finistR2019/)