---
title: "Publications"
output: 
  html_document:
   toc: true
   toc_float: true
   number_sections: false
   highlight: tango
   css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

## 2025

* Célian Monchy, Marie-Pierre  Etienne, Olivier GimenezUsing informative priors to account for identifiability issues in occupancy models with identification errors [Peer Community Journal](https://peercommunityjournal.org/articles/10.24072/pcjournal.511/)


## 2024
* [preprint] Nicolas Bez, Pierre Gloaguen, Marie-Pierre Etienne, Rocio Joo, Sophie Lanco, Etienne Rivot, Emily Walker, Mathieu Woillez, Stéphanie Mahévas. Proper account of auto-correlations improves decoding performances of state-space (semi) Markov models [HAL](https://cnrs.hal.science/hal-04547315/)

* Baptiste Alglave, Maxime Olmos, Juliette Casemajor, Marie-Pierre Etienne, Etienne Rivot, Mathieu Woillez, Youen Vermard. Investigating fish reproduction phenology and essential habitats by identifying the main spatio-temporal patterns of fish distribution. [ICES Journal of Marine Science](https://academic.oup.com/icesjms/article/81/8/1563/7727978)

* [preprint] Baptiste Alglave, Bastien Mourguiart, Kasper Kristensen, Etienne Rivot, Mathieu Woillez, Youen Vermard, Marie-Pierre Etienne. Change of support for heavy-tailed zero inflated data: application to spatially aggregated ecological data for fine-scale species distribution inference. [Hal](https://hal.science/hal-04626952/file/JRSSC_COS.pdf)

* Léa Pautrel, Sylvain Moulherat, Olivier Gimenez, Marie-Pierre Etienne. Analysing biodiversity observation data collected in continuous time: Should we use discrete- or continuous-time occupancy models? [Methods in Ecology and Evolution](https://besjournals.onlinelibrary.wiley.com/doi/pdfdirect/10.1111/2041-210x.14314)

* [preprint] Abel Louis MASSON, Kevan Rastello, Ambre Sacco-Martret de Preville, Yann Tricault, Sylvain Poggi, Elsa Canard, Marie-Pierre Etienne, Manuel Plantegenest. Unveiling the Hidden Feast: translating molecular detection into predation rate. An example on biological control by generalist predators in agricultural fields. [bioRxiv](https://www.biorxiv.org/content/10.1101/2024.11.18.624133v1.full.pdf)



## 2023
*  [preprint] Marie Du Roy de Chaumaray, Salima El Kolei, Marie-Pierre Etienne, Matthieu Marbac. Estimation of the Order of Non-Parametric Hidden Markov Models using the Singular Values of an Integral Operator. [arXiv](https://arxiv.org/abs/2210.03559)

*  [preprint] Léa Pautrel, Sylvain Moulherat, Olivier Gimenez, Marie-Pierre Etienne. Analysing biodiversity observation data collected in continuous time: Should we use discrete or continuous-time occupancy models? [bioRxiv](https://www.biorxiv.org/content/biorxiv/early/2023/11/17/2023.11.17.567350.full.pdf)

*  [preprint] Baptiste Alglave, Kasper Kristensen, Etienne Rivot, Mathieu Woillez, Youen Vermard, Marie-Pierre Etienne. Inferring fine scale wild species distribution from spatially aggregated data [hal](https://hal.science/hal-03878990/document).

* Alice Martin, Marie-Pierre Étienne, Pierre Gloaguen, Sylvain Le Corff, Jimmy Olsson.
Backward Importance Sampling for Online Estimation of State Space Models [Journal of Computational and Graphical Statistics](https://www.tandfonline.com/doi/abs/10.1080/10618600.2023.2174125)

* Baptiste Alglave, Youen Vermard, Etienne Rivot, Marie-Pierre Etienne, Matthieu Woillez. Identifying fish spawning grounds by combining catch declarations and scientific survey data, [Canadian Journal of Fisheries and Aquatic Sciences, janvier 2023](https://cdnsciencepub.com/doi/abs/10.1139/cjfas-2022-0110)



## 2022

* Maxime Jeanjean, Sylvaine Goix, Julien Dron, Marine Periot, Annabelle Austruy, Khaled Douib, Renaud Persoons, Marie-Pierre Etienne, Gautier Revenko, Philippe Chamaret. Influence of Environmental and Dietary Exposures on Metals Accumulation Among the Residents of a Major Industrial Harbour (Fos-sur-Mer, France) accepted in [Journal of Trace Elements in Medicine and Biology](https://www.sciencedirect.com/science/article/pii/S0946672X22001018). 

*  [preprint] Baptiste Alglave, Youen Vermard, Etienne Rivot, Marie-Pierre Etienne, Matthieu Woillez Woillez. Identifying fish spawning grounds by combining catch declarations and scientific survey data [pdf](https://hal.archives-ouvertes.fr/hal-03674691/document).

* Baptiste Alglave, Etienne Rivot, Marie-Pierre Etienne, Mathieu Woillez, Youen Vermard.  Combining scientific survey and commercial catch data to map fish distribution. [ICES Journal of Marine Science, Volume 79, Issue 4, May 2022, Pages 1133–1149](https://academic.oup.com/icesjms/article/79/4/1133/6543974)

* [Book Chapter] Marie-Pierre Etienne and Pierre Gloaguen. Trajectory Reconstruction and Behavior Identification Using Geolocation Data  in the book *Statistical Approaches for Hidden Variables in Ecology* co edited by Olivier Gimenez and Nathalie Peyrard [ici](https://www.iste.co.uk/book.php?id=1859)








## Before 2021


- 2021. Marie-Pierre Etienne. The Hidden part of Markovian Stochastic processes for Biology and Ecology [pdf](MesPapiers/2021_hdr_etienne.pdf)



- 2021. Jeanjean, M., Goix, S., Periot, M., Douib, K., Dron, J., Etienne, M. P., ... & Chamaret, P. (2021). Environmental and Dietary Exposures Near a Major Industrial Harbour (Fos-sur-Mer, France) Identified as a Significant Pathway for PCBs and PCDD/Fs Accumulation in Residents’ Blood Serum. [Exposure and Health, 1-18.](https://link.springer.com/article/10.1007/s12403-021-00395-8)


- 2021. F. Behivoke, MP Etienne, J Guitton, R M Randriatsara, E Ranaivoson, M Léopold. Estimating fishing effort in small-scale fisheries using GPS tracking data and random forests. [Ecological Indicators. 123 (2021) 107321](https://www.sciencedirect.com/science/article/pii/S1470160X20312632)


- 2021. R Joo, N Bez, MP Etienne, P Marin, N Goascoz, J Roux, S Mahévas. Identifying partners at sea from joint movement metrics of pelagic pair trawlers. [ICES Journal of Marine Science. Volume 78, Issue 5 (2021)](https://academic.oup.com/icesjms/article-abstract/78/5/1758/6276504)

- 2020. J Genitoni, D Vassaux, A Delaunay, S Citerne, L Portillo Lemus,  MP. Etienne, D Renault, S. Stoeckel, D. Barloy, S. Maury. 
Hypomethylation of the aquatic invasive plant, Ludwigia grandiflora subsp. hexapetala mimics the adaptive transition into the terrestrial morphotype. [Physiologia Plantarum 170 (2), 280-298](https://onlinelibrary.wiley.com/doi/abs/10.1111/ppl.13162).

- 2020. N Tysklind, MP Etienne, C Scotti‐Saintagne, A Tinaut, M Casalis, Valerie Troispoux
SO Cazal, L Brousseau, B Ferry, I Scotti. Microgeographic local adaptation and ecotype distributions: The role of selective processes on early life‐history traits in sympatric, ecologically divergent Symphonia populations. [Ecology and evolution 10 (19), 10735-10753](https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.6731)


- 2019. Théo Michelot, Pierre Gloaguen, Paul G. Blackwell and  Marie-Pierre Étienne. The Langevin diffusion as a continuous-time model of animal movement and habitat selection. Methods in Ecology and Evolution 10 (11), 1894-1907. [arXiV](https://arxiv.org/abs/1810.10213)


- 2019. Rémi Patin, Marie-Pierre Étienne, Émilie Lebarbier, Simon Chamaillé-Jammes,Simon Benhamou. Identifying stationary phases in multivariate time-series for highlighting behavioural modes and home range settlements. Journal of Animal Ecology 89 (1), 44-56 [bioRXiv](https://www.biorxiv.org/content/10.1101/444794v1)

- 2018. Marie Perrot-Dockès, Céline Lévy-Leduc, Julien Chiquet, Laure Sansonnet, Margaux Brégère, Marie-Pierre Étienne,  Stéphane Robin, Grégory Genta-Jouve.  [A variable selection approach in the multivariate
linear model: an application to LC-MS
metabolomics data](MesPapiers/2018_Perrot+StatAppliInGenetics.pdf) in *Statistical Applications in Genetics and Molecular Biology*.

- 2018. Rocio Joo, Marie-Pierre Etienne, Nicolas Bez,  Stéphanie Mahévas. [Metrics for describing dyadic movement: a review](MesPapiers/2018_Joo+MovemenetEcology.pdf) *Movement Ecology*

- 2018. Pierre Gloaguen, Marie-Pierre Étienne, Sylvain Le Corff [Online sequential Monte Carlo smoother for partially observed diffusion processes](MesPapiers/2018_Gloaguen+EURASIP.pdf).*EURASIP Journal on Advances in Signal Processing*

- 2017. Pierre Gloaguen, Marie-Pierre Étienne, Sylvain Le Corff [Stochastic differential equation based on a multimodal potential to model movement data in ecology](MesPapiers/2017_Gloaguen+JRSSC.pdf). *JRSSC* 

- 2017. Thomas Denis, Cécile Richard-Hansen, Olivier Brunaux, Marie-Pierre Etienne, , Stéphane Guitet, Bruno Herault [Biological traits, rather than environment, shape detection curves of large vertebrates in neotropical rainforests]()*Ecological Applications*

- 2016. Mia Wege, Marie-Pierre Etienne,  W. Chris Oosthuizen, Ryan R. Reisinger, Marthán N. Bester, P. J. Nico De Bruyn [Trend changes in sympatric Subantarctic and Antarctic fur seal pup populations at Marion Island, Southern Ocean](MesPapiers/2016_Wege+MarineMammalScience.pdf).*Marine Mammal science*

- 2016. Nicolas C. Friggens, Christine Duvaux-Ponter, Marie-Pierre Etienne, Tristan Mary-Huard, Philippe Schmidely.  [Characterizing individual differences in animal responses to a nutritional challenge: Toward improved robustness measures](MesPapiers/2016_Friggens+JDS.pdf). *Journal of Diary Science*


- 2015. Ophélie Sauzet, Cécilia Cammas, Pierre Barbillon, Marie-Pierre Étienne, David Montagne. [Illuviation intensity and land use change: Quantification via micromorphological analysis](MesPapiers/2015_Sauzet+Geoderma.pdf). *Geoderma*.

- 2014. Pierre Gloaguen, Stéphanie Mahévas, Etienne Rivot, Mathieu Woillez, Jérôme Guitton, Youen Vermard, Marie-Pierre Etienne. [An autoregressive model to describe fishing vessel movement and activity](MesPapiers/2014_Gloaguen+Environmetrics.pdf). *Environmetrics*.

- 2014. Olivier Gimenez, Stephen T. Buckland, Byron J. T. Morga, Nicolas Bez, Sophie Bertrand, Rémi Choquet, Stéphane Dray, Marie-Pierre Etienne, Rachel Fewster, Frédéric Gosselin, Bastien Mérigot, Pascal Monestiez,  Juan M. Morales, Frédéric Mortier, François Munoz, Otso Ovaskainen,
Sandrine Pavoine, Roger Pradel, Frank M. Schurr, Len Thomas, Wilfried Thuiller, Verena Trenkel,Perry de Valpine , Eric Rexstad. [Statistical ecology comes of age](MesPapiers/2014_Gimenez+BiologyLetters.pdf). *Biology Letters*


- 2013. Jean-Baptiste Lecomte, Hugues P. Benoît, Sophie Ancele,  Marie-Pierre Etienne, Liliane Bel, Eric Parent.[Compound Poisson-gamma vs. delta-gamma to handle zero-inflated continuous data under a variable sampling volume](2013_Lecomte+Methods_in_Ecology_and_Evolution.pdf). *Methods in Ecology and Evolution*

- 2013. Jean-Baptiste Lecomte, Hugues P. Benoît, Marie-Pierre Etienne, Liliane  Bel, Eric Parent.[Modeling the habitat associations and spatial distribution of benthic
macroinvertebrates: A hierarchical Bayesian model for zero-inflated
biomass data](MesPapiers/2013_Lecomte+EcologicalModelling.pdf). *Ecological Modelling*

- 2012. Maximilien Simon, Jean-Marc Fromentin, Sylvain Bonhommeau, Daniel Gaertner, Jon Brodziak, Marie-Pierre Etienne [Effects of Stochasticity in Early Life History on Steepness and Population Growth Rate Estimates: An Illustration on Atlantic Bluefin Tuna](MesPapiers/2012_Simon+PlosOne.pdf). *Plos One*

- 2011. J. Matias Braccini, Marie-Pierre Etienne,  Steve . J. D. Martell. [Subjective judgement in data subsetting: implications for CPUE standardisation and stock assessment of non-target chondrichthyans](MesPapiers/2011_Braccini+Marine_and_Freshwater_Research.pdf). *Marine and Freshwater Research*


- 2010. Sophie Ancelet, Marie-Pierre Etienne, Hugues Benoît, Eric Parent. [Modelling spatial zero-inflated continuous data with an exponentially compound Poisson process](MesPapiers/2010_Ancelet+ESS.pdf).*Environmental and Ecological Statistics*

- 2009. Sarah Groc, Jérôme Orivel, Alain Dejean, Jean-Michel Martin, Marie-Pierre Etienne, Bruno Corbara, Jacques H. C. Delabie.[Baseline study of the leaf-litter ant fauna in a French Guianese forest](MesPapiers/2009_Groc+icad.pdf). *Insect Conservation and Diversity*

- 2004. Marie-Pierre Etienne, Pierre Vallois [Approximation of the Distribution of the Supremum of a Centered Random Walk. Application to the Local Score](MesPapiers/2004_Etienne+MCAP.pdf). *Methodology and Computing in Applied Probability*

- 2003. Jean-Jacques Daudin, Marie-Pierre Etienne, Pierre Vallois. [Asymptotic behavior of the local score of independent and identically distributed random sequences](MesPapiers/2003_Daudin+SPA.pdf). *Stochastic Processes and their Applications*
