---
title: "Teaching materials"
output: 
  html_document:
   toc: true
   toc_float: true
   # logo: LogoAgrocampusOuest.jpg
   number_sections: false
   highlight: tango
   css: style.css
---




```{r setup_teaching, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

# Démarche statistique - partie 2

Ce cours constitue la seconde partie du module de démarche statistique. Les supports des quatre cours sont

- [Régression multiple](http://marieetienne.github.io/demarche_stat_partie2/_presentation/regression.html)

- [Analyse de la variance à deux facteurs](http://marieetienne.github.io/demarche_stat_partie2/_presentation/anova2.html)

- [Analyse en compostaes principales](http://marieetienne.github.io/demarche_stat_partie2/_presentation/acp.html)

- [Plan d'expérience](http://marieetienne.github.io/demarche_stat_partie2/_presentation/plan_exp.html)


Les  TD correspondants sont les TD 11 à 17 disponibles sur la page des [énonces de TD](https://agrocampusds.github.io/demarche_statistique/)


# M2 Datascience


## Outils pour la science reproductible

[Ce cours](https://marieetienne.github.io/reproductibilite/) propose une introduction à l'utilisation du système de version 
[git](https://git-scm.com/) dans un objectif de produire de la science reproductible.


## Modélisation bayésienne pour l'écologie

Cours de statistique pour les étudiants de la spécialisation Science des données et MODE.

Les slides sont disponibles [ici](https://marieetienne.github.io/bayesian_and_ecology/_presentation/#1)

Rappel sur quelques lois de probabilités classiques et utiles dans les approches bayésiennes [ici](slides/LoiProbas.pdf)

Script du TD comptage [ici](slides/TD_Pup2.pdf) 



# Cours ED EGAAL

## Modelisation statistique 

Formation dispensée dans le cadre de l'école doctorale EGAAL. Cette formation est destinée à des étudiants en thèse dans le domaine des sciences du vivant et qui souhaiterait recevoir une formation complémentaire en modélisation statistique. La formation est organisée en 2 séquences d'une semaine chacune et il est important de s'engager à participer à l'intégralité de ces deux semaines. 

- [Le cours d'introduction à R](slides/mod_stat_jour1.pdf) 
- [Modèle linéaire](slides/mod_stat_jour2.pdf) 
- [Modèle linéaire  généralisé](slides/mod_stat_jour4.pdf)
- [Modèle mixte](slides/mod_stat_jour5.pdf)
- Des [exemples](https://marieetienne.github.io/ModStat/)

        

